#Librerias de Pandas

### LIBRERIA NumPy

In [1]:
numero = []

In [2]:
numero.append(1)
numero.append(2)
numero.append(3)
numero.append(4)

In [3]:
numero

[1, 2, 3, 4]

#### Repeticion de numeros

In [4]:
numero * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [5]:
numero * 5

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

#### Recorriendo numeros de la lista

In [12]:
for i in numero:
    print(i)

1
2
3
4


#### Multiplicando los numeros de la lista

In [11]:
for i in numero:
    print(i * 2)

2
4
6
8


In [13]:
for i in numero:
    print(i * 5)

5
10
15
20


#### Sumando numeros

In [14]:
for i in numero:
    print(i + 2)

3
4
5
6


In [15]:
for i in numero:
    print(i + 5)

6
7
8
9


#### Restando numeros

In [17]:
for i in numero:
    print(i - 2)

-1
0
1
2


In [18]:
for i in numero:
    print(i - 5)

-4
-3
-2
-1


### Ahora aplicamos la libreria NumPy

In [19]:
import numpy as np

### Creando arreglo con NumPy

In [22]:
numero = np.array([1,2,3,4])

In [23]:
numero

array([1, 2, 3, 4])

In [24]:
numero * 2

array([2, 4, 6, 8])

In [25]:
numero + 5

array([6, 7, 8, 9])

In [26]:
numero - 1

array([0, 1, 2, 3])

In [29]:
list1 = np.arange(1_000)
list2 = list(range(1_000))

#### Tiempo que toma a numPy realizar calculos

In [32]:
%timeit list2 - list1 *2

60.3 µs ± 4.69 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [35]:
%timeit list2 = [x * 2 for x in list1]

146 µs ± 34.7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Ndarray (cantidad de dimenciones q tienen los arreglos)

#### Creando los arreglos en dos dimensiones

In [37]:
data = np.array([[1,2,3],[4,5,6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

### Operaciones matematicas

In [38]:
data * 10

array([[10, 20, 30],
       [40, 50, 60]])

#### ndim (cantidad de dimensiones que tiene un arreglo)

In [39]:
data.ndim

2

### shape(filas x columnas)

In [40]:
data.shape

(2, 3)

### Creando un arreglo de tres dimensiones

In [55]:
dim1 = np.array([1,2,3])
dim2 = np.array([[1,2,3],[4,5,6]])
dim3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [56]:
dim1

array([1, 2, 3])

In [57]:
dim2

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
dim3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [59]:
print(dim1.ndim)
print(dim2.ndim)
print(dim3.ndim)

1
2
3


In [60]:
print(dim1.shape)
print(dim2.shape)
print(dim3.shape)

(3,)
(2, 3)
(2, 2, 3)


## Data type

In [61]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [62]:
dim3_float = dim3.astype(np.float64)
dim3_float

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]])

### Index y Slicing

In [63]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
data[2:8] # solicitando numeros 2 entre 8 posiciones

array([2, 3, 4, 5, 6, 7])

In [67]:
data[2] = 40 # En posicion 2 agregamos el numero 40
data

array([ 0,  1, 40,  3,  4,  5,  6,  7,  8,  9])

#### Cambiando el valor del arreglo

In [68]:
data[:] = 100
data

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [69]:
dim2

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
dim2[0] # posicion cero

array([1, 2, 3])

In [78]:
dim2[0][2]  # indexando fila 0 por columna 2

np.int64(3)

In [80]:
dim2[:2] # muestra las filas

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
dim2[:2, :1] # muestra las filas y columnas de esa posicion

array([[1],
       [4]])

In [81]:
dim3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [84]:
dim3[1] # devuelve las dos ultimas filas

array([[ 7,  8,  9],
       [10, 11, 12]])

In [85]:
dim3[1][1] # se accede a la ultima fila de la matriz

array([10, 11, 12])

In [86]:
dim3[1][1][2] # seguimos en la ultima fila de la matriz y accedemos a la posicion 2

np.int64(12)

### Otra forma de acceder a la matriz y posicion

In [87]:
dim3[1, 1, 2]

np.int64(12)

#### Indexacion booleana

In [88]:
texto = np.array(["cero", "uno", "uno", "cero", "cero", "uno"])
data = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])

In [89]:
texto == 'uno'

array([False,  True,  True, False, False,  True])

In [90]:
data[texto == 'uno']

array([[ 3,  4],
       [ 5,  6],
       [11, 12]])

In [91]:
data[texto == 'uno', :1]  # se realiza indexacion de la primera columna

array([[ 3],
       [ 5],
       [11]])

In [92]:
data[~(texto == 'uno')] # se realiza la inversa de la indexacion

array([[ 1,  2],
       [ 7,  8],
       [ 9, 10]])

## Transposicion de los arreglos

#### Cambia la forma de un arreglo sin necesidad de copiar el mismo arregloS

In [95]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [94]:
arr = np.arange(15).reshape((3,5)) # Colocamos 15 numeros
arr       # reshape vamos a dar la forma de 3 filas y 5 columnas

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

##### Importate !!!
A la hora de usar el reshape se tiene que tener en cuenta la cantidad de valores q se estan por usar

### Transposicion de los arreglos

In [99]:
arr.T # METODO T cambia la forma de la matriz de 3 x 5 a 5 x 3

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [100]:
np.dot(arr.T, arr) # realiza el producto punto de la matriz

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [102]:
arr_t = arr.T @ arr # otra forma de armar el arreglo
arr_t

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

## Indexaxion con boloeanos

In [103]:
arr_t > 450

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [104]:
arr_t >100

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [106]:
np.where(arr_t > 150, 1, 0)

array([[0, 0, 1, 1, 1],
       [0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [108]:
False + 1 # el velor de false es cero y si se le suma 1 es igual a 1

1

In [109]:
True + 1 # el valor de true es igual a 1 y si se le suma 1 es igual a 2

2

In [110]:
arr_t.mean() # promedio de la matriz

np.float64(197.0)

In [111]:
np.mean(arr_t) # otra forma de calcular el promedio

np.float64(197.0)

In [113]:
arr_t.mean(axis=1) # promedio de cada una de las filas

array([155., 176., 197., 218., 239.])

In [114]:
arr_t.mean(axis=0) # promedio de cada una de las columnas

array([155., 176., 197., 218., 239.])

In [115]:
arr_t.sum() # suma de todos los valores de la matriz

np.int64(4925)

In [116]:
arr_t.cumsum(axis=0) # suma acumulada de cada una de las columnas

array([[ 125,  140,  155,  170,  185],
       [ 265,  298,  331,  364,  397],
       [ 420,  474,  528,  582,  636],
       [ 590,  668,  746,  824,  902],
       [ 775,  880,  985, 1090, 1195]])

In [117]:
arr_t.cumsum(axis=1) # suma acumulada de cada una de las filas

array([[ 125,  265,  420,  590,  775],
       [ 140,  298,  474,  668,  880],
       [ 155,  331,  528,  746,  985],
       [ 170,  364,  582,  824, 1090],
       [ 185,  397,  636,  902, 1195]])

In [118]:
arr_t.cumprod(axis=0) # producto acumulado de cada una de las columnas

array([[         125,          140,          155,          170,
                 185],
       [       17500,        22120,        27280,        32980,
               39220],
       [     2712500,      3893120,      5374160,      7189640,
             9373580],
       [   461125000,    755265280,   1171566880,   1739892880,
          2493372280],
       [ 85308125000, 160116239360, 280004484320, 462811506080,
        730558078040]])

In [119]:
arr_t.cumprod(axis=1) # producto acumulado de cada una de las filas

array([[         125,        17500,      2712500,    461125000,
         85308125000],
       [         140,        22120,      3893120,    755265280,
        160116239360],
       [         155,        27280,      5374160,   1171566880,
        280004484320],
       [         170,        32980,      7189640,   1739892880,
        462811506080],
       [         185,        39220,      9373580,   2493372280,
        730558078040]])

In [121]:
arr = np.random.standard_normal((5,3)) # genera numeros aleatorios
arr

array([[ 0.1909933 ,  1.57882916, -0.30873479],
       [-0.63623918,  1.89683425,  0.93278696],
       [-0.24864102,  0.55383018, -1.49996745],
       [ 0.34213685, -1.25983672, -0.08719355],
       [ 0.1019531 ,  0.77153588, -0.3293241 ]])

In [122]:
arr.sort() # ordena los valores de la matriz
arr

array([[-0.30873479,  0.1909933 ,  1.57882916],
       [-0.63623918,  0.93278696,  1.89683425],
       [-1.49996745, -0.24864102,  0.55383018],
       [-1.25983672, -0.08719355,  0.34213685],
       [-0.3293241 ,  0.1019531 ,  0.77153588]])

In [123]:
arr.sort(axis=0) # ordena los valores de la matriz por columnas
arr

array([[-1.49996745, -0.24864102,  0.34213685],
       [-1.25983672, -0.08719355,  0.55383018],
       [-0.63623918,  0.1019531 ,  0.77153588],
       [-0.3293241 ,  0.1909933 ,  1.57882916],
       [-0.30873479,  0.93278696,  1.89683425]])

In [124]:
arr.sort(axis=1) # ordena los valores de la matriz por filas
arr

array([[-1.49996745, -0.24864102,  0.34213685],
       [-1.25983672, -0.08719355,  0.55383018],
       [-0.63623918,  0.1019531 ,  0.77153588],
       [-0.3293241 ,  0.1909933 ,  1.57882916],
       [-0.30873479,  0.93278696,  1.89683425]])